/** Baseline rows aligned with Farm-front `mockData.cropCalendar` (extend via admin API). */
module.exports = [
  {
    slug: "wheat",
    cropName: "Wheat",
    cropNameHindi: "गेहूं",
    category: "grains",
    season: "winter",
    plantingMonths: [10, 11],
    harvestingMonths: [3, 4],
    growingPeriod: 120,
    description:
      "Winter crop, best planted in October-November. Requires cool weather for growth.",
    descriptionHindi:
      "सर्दियों की फसल, अक्टूबर-नवंबर में लगाना सबसे अच्छा। वृद्धि के लिए ठंडे मौसम की आवश्यकता होती है।",
    tips: [
      "Plant in well-drained soil",
      "Requires 6-8 hours of sunlight",
      "Water regularly but avoid waterlogging",
      "Harvest when grains are golden yellow",
    ],
    tipsHindi: [
      "अच्छी जल निकासी वाली मिट्टी में लगाएं",
      "6-8 घंटे धूप की आवश्यकता",
      "नियमित रूप से पानी दें लेकिन जलभराव से बचें",
      "जब दाने सुनहरे पीले हों तो कटाई करें",
    ],
    icon: "🌾",
    region: "",
    isPublished: true,
    order: 0,
  },
  {
    slug: "rice",
    cropName: "Rice",
    cropNameHindi: "चावल",
    category: "grains",
    season: "monsoon",
    plantingMonths: [6, 7],
    harvestingMonths: [10, 11],
    growingPeriod: 120,
    description:
      "Monsoon crop, planted during June-July. Requires standing water for growth.",
    descriptionHindi:
      "मानसून की फसल, जून-जुलाई के दौरान लगाई जाती है। वृद्धि के लिए खड़े पानी की आवश्यकता होती है।",
    tips: [
      "Requires flooded fields",
      "Plant seedlings in rows",
      "Maintain water level 5-10 cm",
      "Harvest when 80% grains are mature",
    ],
    tipsHindi: [
      "बाढ़ वाले खेतों की आवश्यकता",
      "पंक्तियों में पौधे लगाएं",
      "पानी का स्तर 5-10 सेमी बनाए रखें",
      "जब 80% दाने परिपक्व हों तो कटाई करें",
    ],
    icon: "🌾",
    region: "",
    isPublished: true,
    order: 1,
  },
  {
    slug: "tomato",
    cropName: "Tomato",
    cropNameHindi: "टमाटर",
    category: "vegetables",
    season: "winter",
    plantingMonths: [9, 10, 11],
    harvestingMonths: [12, 1, 2, 3],
    growingPeriod: 90,
    description:
      "Winter vegetable, can be grown year-round. Best quality in winter months.",
    descriptionHindi:
      "सर्दियों की सब्जी, साल भर उगाई जा सकती है। सर्दियों के महीनों में सबसे अच्छी गुणवत्ता।",
    tips: [
      "Start from seeds or seedlings",
      "Requires support stakes",
      "Water at base, avoid leaves",
      "Harvest when fully red",
    ],
    tipsHindi: [
      "बीज या पौध से शुरू करें",
      "सहारा खूंटे की आवश्यकता",
      "जड़ में पानी दें, पत्तियों से बचें",
      "पूरी तरह लाल होने पर कटाई करें",
    ],
    icon: "🍅",
    region: "",
    isPublished: true,
    order: 2,
  },
  {
    slug: "onion",
    cropName: "Onion",
    cropNameHindi: "प्याज",
    category: "vegetables",
    season: "winter",
    plantingMonths: [10, 11],
    harvestingMonths: [2, 3, 4],
    growingPeriod: 120,
    description:
      "Winter crop, planted in October-November. Long growing season required.",
    descriptionHindi:
      "सर्दियों की फसल, अक्टूबर-नवंबर में लगाई जाती है। लंबे बढ़ते मौसम की आवश्यकता।",
    tips: [
      "Plant bulbs or sets",
      "Well-drained sandy soil",
      "Stop watering 2 weeks before harvest",
      "Harvest when tops fall over",
    ],
    tipsHindi: [
      "बल्ब या सेट लगाएं",
      "अच्छी जल निकासी वाली रेतीली मिट्टी",
      "कटाई से 2 सप्ताह पहले पानी देना बंद करें",
      "जब ऊपरी हिस्सा गिर जाए तो कटाई करें",
    ],
    icon: "🧅",
    region: "",
    isPublished: true,
    order: 3,
  },
  {
    slug: "potato",
    cropName: "Potato",
    cropNameHindi: "आलू",
    category: "vegetables",
    season: "winter",
    plantingMonths: [10, 11],
    harvestingMonths: [1, 2, 3],
    growingPeriod: 90,
    description: "Winter crop, planted in October-November. Requires cool climate.",
    descriptionHindi:
      "सर्दियों की फसल, अक्टूबर-नवंबर में लगाई जाती है। ठंडे जलवायु की आवश्यकता।",
    tips: [
      "Plant seed potatoes",
      "Hilling required during growth",
      "Keep soil moist but not wet",
      "Harvest when plants die back",
    ],
    tipsHindi: [
      "बीज आलू लगाएं",
      "वृद्धि के दौरान मिट्टी चढ़ाना आवश्यक",
      "मिट्टी को नम रखें लेकिन गीला नहीं",
      "जब पौधे मर जाएं तो कटाई करें",
    ],
    icon: "🥔",
    region: "",
    isPublished: true,
    order: 4,
  },
  {
    slug: "mango",
    cropName: "Mango",
    cropNameHindi: "आम",
    category: "fruits",
    season: "summer",
    plantingMonths: [6, 7, 8],
    harvestingMonths: [4, 5, 6],
    growingPeriod: 365,
    description:
      "Summer fruit, trees planted in monsoon. Fruits available April-June.",
    descriptionHindi:
      "गर्मियों का फल, मानसून में पेड़ लगाए जाते हैं। अप्रैल-जून में फल उपलब्ध।",
    tips: [
      "Plant grafted saplings",
      "Requires 3-4 years to fruit",
      "Prune after harvest",
      "Harvest when slightly soft",
    ],
    tipsHindi: [
      "कलम वाले पौधे लगाएं",
      "फल देने में 3-4 साल लगते हैं",
      "कटाई के बाद छंटाई करें",
      "थोड़ा नरम होने पर कटाई करें",
    ],
    icon: "🥭",
    region: "",
    isPublished: true,
    order: 5,
  },
  {
    slug: "banana",
    cropName: "Banana",
    cropNameHindi: "केला",
    category: "fruits",
    season: "monsoon",
    plantingMonths: [6, 7, 8],
    harvestingMonths: [9, 10, 11, 12],
    growingPeriod: 270,
    description: "Year-round crop, best planted in monsoon. Quick growing cycle.",
    descriptionHindi:
      "साल भर की फसल, मानसून में लगाना सबसे अच्छा। तेज़ बढ़ने वाला चक्र।",
    tips: [
      "Plant suckers or tissue culture",
      "Requires regular watering",
      "Support with stakes when fruiting",
      "Harvest when fingers are full",
    ],
    tipsHindi: [
      "सकर्स या टिशू कल्चर लगाएं",
      "नियमित पानी की आवश्यकता",
      "फल लगने पर खूंटे से सहारा दें",
      "जब उंगलियां भरी हों तो कटाई करें",
    ],
    icon: "🍌",
    region: "",
    isPublished: true,
    order: 6,
  },
  {
    slug: "cotton",
    cropName: "Cotton",
    cropNameHindi: "कपास",
    category: "other",
    season: "monsoon",
    plantingMonths: [5, 6],
    harvestingMonths: [10, 11, 12],
    growingPeriod: 150,
    description: "Monsoon crop, planted in May-June. Long growing season.",
    descriptionHindi:
      "मानसून की फसल, मई-जून में लगाई जाती है। लंबा बढ़ने वाला मौसम।",
    tips: [
      "Plant in warm climate",
      "Requires good spacing",
      "Control pests regularly",
      "Harvest when bolls open",
    ],
    tipsHindi: [
      "गर्म जलवायु में लगाएं",
      "अच्छी दूरी की आवश्यकता",
      "नियमित रूप से कीट नियंत्रण",
      "जब फल खुल जाएं तो कटाई करें",
    ],
    icon: "🌿",
    region: "",
    isPublished: true,
    order: 7,
  },
  {
    slug: "sugarcane",
    cropName: "Sugarcane",
    cropNameHindi: "गन्ना",
    category: "other",
    season: "monsoon",
    plantingMonths: [2, 3, 4, 5],
    harvestingMonths: [12, 1, 2, 3],
    growingPeriod: 365,
    description:
      "Year-round crop, planted February-May. Takes 10-12 months to mature.",
    descriptionHindi:
      "साल भर की फसल, फरवरी-मई में लगाई जाती है। परिपक्व होने में 10-12 महीने लगते हैं।",
    tips: [
      "Plant stem cuttings",
      "Requires abundant water",
      "Fertilize regularly",
      "Harvest when fully mature",
    ],
    tipsHindi: [
      "तने की कटिंग लगाएं",
      "प्रचुर पानी की आवश्यकता",
      "नियमित रूप से उर्वरक डालें",
      "पूरी तरह परिपक्व होने पर कटाई करें",
    ],
    icon: "🌾",
    region: "",
    isPublished: true,
    order: 8,
  },
  {
    slug: "chilli",
    cropName: "Chilli",
    cropNameHindi: "मिर्च",
    category: "spices",
    season: "winter",
    plantingMonths: [8, 9, 10],
    harvestingMonths: [11, 12, 1, 2],
    growingPeriod: 90,
    description: "Winter crop, planted August-October. Can be grown year-round.",
    descriptionHindi:
      "सर्दियों की फसल, अगस्त-अक्टूबर में लगाई जाती है। साल भर उगाई जा सकती है।",
    tips: [
      "Start from seeds",
      "Requires warm weather",
      "Harvest regularly for more yield",
      "Dry for storage",
    ],
    tipsHindi: [
      "बीज से शुरू करें",
      "गर्म मौसम की आवश्यकता",
      "अधिक उपज के लिए नियमित कटाई",
      "भंडारण के लिए सुखाएं",
    ],
    icon: "🌶️",
    region: "",
    isPublished: true,
    order: 9,
  },
  {
    slug: "turmeric",
    cropName: "Turmeric",
    cropNameHindi: "हल्दी",
    category: "spices",
    season: "monsoon",
    plantingMonths: [4, 5],
    harvestingMonths: [1, 2],
    growingPeriod: 270,
    description: "Monsoon crop, planted April-May. Harvested after 9 months.",
    descriptionHindi:
      "मानसून की फसल, अप्रैल-मई में लगाई जाती है। 9 महीने बाद कटाई।",
    tips: [
      "Plant rhizomes",
      "Requires shade",
      "Keep soil moist",
      "Harvest when leaves dry",
    ],
    tipsHindi: [
      "प्रकंद लगाएं",
      "छाया की आवश्यकता",
      "मिट्टी को नम रखें",
      "जब पत्तियां सूख जाएं तो कटाई करें",
    ],
    icon: "🟡",
    region: "",
    isPublished: true,
    order: 10,
  },
  {
    slug: "lentil",
    cropName: "Lentil (Masoor)",
    cropNameHindi: "मसूर दाल",
    category: "pulses",
    season: "winter",
    plantingMonths: [10, 11],
    harvestingMonths: [2, 3],
    growingPeriod: 120,
    description:
      "Winter pulse, planted October-November. Good source of protein.",
    descriptionHindi:
      "सर्दियों की दाल, अक्टूबर-नवंबर में लगाई जाती है। प्रोटीन का अच्छा स्रोत।",
    tips: [
      "Plant in well-drained soil",
      "Requires less water",
      "Fix nitrogen in soil",
      "Harvest when pods turn brown",
    ],
    tipsHindi: [
      "अच्छी जल निकासी वाली मिट्टी में लगाएं",
      "कम पानी की आवश्यकता",
      "मिट्टी में नाइट्रोजन स्थिर करें",
      "जब फली भूरी हो जाए तो कटाई करें",
    ],
    icon: "🫘",
    region: "",
    isPublished: true,
    order: 11,
  },
  {
    slug: "chickpea",
    cropName: "Chickpea (Chana)",
    cropNameHindi: "चना",
    category: "pulses",
    season: "winter",
    plantingMonths: [10, 11],
    harvestingMonths: [2, 3, 4],
    growingPeriod: 120,
    description:
      "Winter pulse, planted October-November. Popular in Indian cuisine.",
    descriptionHindi:
      "सर्दियों की दाल, अक्टूबर-नवंबर में लगाई जाती है। भारतीय व्यंजनों में लोकप्रिय।",
    tips: [
      "Plant in rows",
      "Requires moderate water",
      "Control weeds regularly",
      "Harvest when plants dry",
    ],
    tipsHindi: [
      "पंक्तियों में लगाएं",
      "मध्यम पानी की आवश्यकता",
      "नियमित रूप से खरपतवार नियंत्रण",
      "जब पौधे सूख जाएं तो कटाई करें",
    ],
    icon: "🫘",
    region: "",
    isPublished: true,
    order: 12,
  },
];
